- name: create /usr/java directory
  file: path=/usr/java state=directory owner=root group=root mode=0755
  tags: java7

- name: check jdk7 package downloaded
  command: test -f {{ src_base_dir }}/jdk-{{ jdk7_pkg_version }}-linux-x64.tar.gz
  register: jdk7_downloaded
  failed_when: jdk7_downloaded.rc not in [0, 1]
  changed_when: False
  tags: java7

- name: download jdk7 package
  command: >
    wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz" -O {{ src_base_dir }}/jdk-{{ jdk7_pkg_version }}-linux-x64.tar.gz
  tags: java7
  when: jdk7_downloaded.rc == 1

- name: extract jdk7
  command: >
    tar -xf {{ src_base_dir }}/jdk-{{ jdk7_pkg_version }}-linux-x64.tar.gz
    chdir=/usr/java
    creates=/usr/java/jdk{{ jdk7_version }}
  tags: java7

- name: symlink to /usr/local
  file: >
    state=link
    src=/usr/java/jdk{{ jdk7_version }}
    dest=/usr/local/{{  symlink_to  }}
    owner=root group=root
  tags: java7
